# version: "1"
services:
  client:
    build: ./client/
    image: k3mboi/client:v1.0.1
    container_name: yolo_client
    ports:
      - "3000:3000"
    networks:
      - yolo_network
    depends_on:
      - backend
  
  backend:
    build: ./backend/
    image: k3mboi/backend:v1.0.0
    container_name: yolo_backend
    ports:
      - "5000:5000"
    networks:
      - yolo_network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: yolo_mongo
    ports:
      - "27017:27017"
    volumes:
      - database_data:/data/db
    networks:
      - yolo_network
    environment:
      MONGO_INTDB_ROOT_USERNAME: BrianKemboi
      MONGO_INTDB_ROOT_PASSWORD: KemboiAccess1
      MONGO_INITDB_DATABASE: yolodb
volumes:
  database_data:
    driver: local

networks:
  yolo_network:
    driver: bridge