---
 -  name: Playbook to dockerize and  application
    hosts: all
    become: true
    roles:
      - packages_setup
      - mongo-setup
      - backend-deployment
      - frontend-deployment
      