--- 
- name: pull frontend code
  community.docker.docker_image:
    name: "{{docker_image}}"
    tag: latest
    source: pull


- name: run frontend container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "{{ docker_image }}"
    state: started
    networks:
      - name: "{{ network_name }}"
    ports:
      - "3000:3000"
    command: "npm start"
  