---
- name: install git
  ansible.builtin.apt:
    name: git
    state: present 
  tag: ['packages_setup'] 

- name: clone the repository
  ansible.builtin.git:
    repo: "{{ github_repository }}"
    dest: "{{ destination_directory }}"
  tag: ['packages_setup']

- name: Add Docker GPG apt Key
  apt_key:
    url: "{{ docker_gpg }}"
    state: present
  tag: ['packages_setup']

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
  tag: ['packages_setup']

- name: install dependencies
  ansible.builtin.apt:
    name: "{{ packages }}"
    update_cache: true
    state: present
  become: true
  tag: ['packages_setup']

- name: Create Docker network for application
  docker_network:
    name: "{{ network_name }}"
    state: present
  tag: ['network_setup']
        
