#backend deployment manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        tier: backend
    spec:
      containers:
      - name: backend
        image: k3mboi/backend:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URL
          value: "mongodb://BrianKemboi:KemboiAccess1@mongodbservice:27017/yolodb?authSource=admin"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m" 
---